name: mox_digital_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  http: ^1.2.0
  webview_flutter: ^4.7.0
  file_picker: ^8.0.0
  # حزم الخزينة وقاعدة البيانات المحلية بالمسطرة
  sqflite: ^2.3.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # حزمة توليد الأيقونات السيادية بالمسطرة
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  # تفعيل الأصول السيادية بالمسطرة
  assets:
    - assets/logo.png
    - assets/mox_app_icon.png

  # تفعيل الخطوط من مجلد Cairo الخاص بك
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

# إعدادات الأيقونة الرسمية للتطبيق بالمسطرة
flutter_launcher_icons:
  image_path: "assets/mox_app_icon.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/mox_app_icon.png"